### DISCUSSION TITLE
Not able to deploy on k8s with GKE ingress.

### DISCUSSION THREAD

**Discussion by ghost** [osm-search/Nominatim#2901] [Q&A]
Not able to run it on k8s. I am using helm method to install. 

```
--- 
updateStrategy:
  type: Recreate

nominatimInitialize:
  enabled: false
  pbfUrl: http://download.geofabrik.de/asia/india/central-zone-latest.osm.pbf
  importWikipedia: false
  importGB_Postcode: false
  importUS_Postcode: false
  importStyle: full
  threads: 16
  freeze: false
  
postgresql: 
  enabled: false
  
externalDatabase: 
    database: nominatim
    host: 10.47.112.3
    password: jwvdvkqvfuy7389
    port: 5432
    user: postgres

service:
  type: NodePort
  port: 8081
```
