### DISCUSSION TITLE
Postgres database huge after intial import

### DISCUSSION THREAD

**Discussion by tlaugier** [osm-search/Nominatim#3271] [Q&A]
Hi everyone, I just installed a new server and did the initial import for the planet with the address "data style". According to [the docs](https://nominatim.org/release-docs/latest/admin/Import/#filtering-imported-data) I should be looking at 545 GB of db size but my db is actually 1537 GB!
Is there some cleanup I should be doing after the initial import? I don't think the `--drop` option is correct for my use case since I plan on doing daily updates on this server.
I'm using the following docker compose file for my server:
```yml
version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.3
        restart: always
        ports:
            - "127.0.0.1:8080:8080"
            - "5432:5432"
        environment:
            PBF_URL: https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
            REPLICATION_URL: https://planet.openstreetmap.org/replication/day/
            UPDATE_MODE: "continuous"
            IMPORT_STYLE: "address"
            THREADS: 32
            POSTGRES_MAX_WAL_SIZE: "4GB"
        volumes:
            - type: bind
              source: /data/nominatim/db
              target: /var/lib/postgresql/14/main
            - type: bind
              source: /data/nominatim/nominatim_data
              target: /nominatim
        shm_size: 16gb
```
