### ISSUE TITLE
psycopg2.OperationalError: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by tamis-laan** [osm-search/Nominatim#2778]
I'm using docker to run a nominatim instance:
``` yaml
  # Nominatim geocoder
  nominatim:
    image: mediagis/nominatim:4.0
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    environment:
      PBF_URL: https://download.geofabrik.de/europe/netherlands-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/netherlands-updates/
    shm_size: 3gb
    restart: always
    deploy:
      resources:
        limits:
          memory: 6G
```
At first start the container starts the indexing process, after hours and hours is crashes. I attached a screenshot to show the output:
![screenshot](https://user-images.githubusercontent.com/3178666/181012257-c6122897-8bb7-418e-b8a3-d7c368a83cbb.png)

It then restarts and drops the database content.

**Hardware Configuration (please complete the following information):**
- RAM: 8GiG 
- number of CPUs: 4
- type and size of disks: ssd 
- bare metal/AWS/other cloud service: Vultr
