### ISSUE TITLE
Add query preprocessor for using regular expressions on queries

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#3663]
[Query preprocessors](https://nominatim.org/release-docs/develop/develop/ICU-Tokenizer-Modules/#custom-query-preprocessors) allow to change an incoming query before it is parsed by Nominatim.

We could do with a generic preprocessor which takes a list of regular expressions and replacements and executes those on each phrase. Configuration should look something like this:

```
query-preprocessing:
    - step: regex_replace
      replacements:
        - pattern: foo
          replace: bar
        - pattern: ([a-z]+) *([a-z]+)
          replace: \1\2
```

Some extra flags might be needed. Things that come in mind are replace-one vs. replace-all and ignoring case.

The replacements should be applied in the order they are given. If the phrase is empty after a replacement, it should be removed from the list.

Use the [japanese preprocessor](https://github.com/osm-search/Nominatim/blob/master/src/nominatim_api/query_preprocessing/split_japanese_phrases.py) as an example for writing a preprocessor and don't forget to add tests (just like https://github.com/osm-search/Nominatim/blob/master/test/python/api/query_processing/test_split_japanese_phrases.py).
